### ISSUE TITLE
Ubuntu GPU 环境下多进程运行时内存增长问题

### ISSUE THREAD

**Issue by iminders** [tradingAI/tbase#7]
origin issue: https://github.com/iminders/tbase/issues/6
系统环境

Ubuntu 18.04
GPU: GTX 1080
Memory: 8G

运行命令： python3 -m tbase.run --num_env 2

错误信息：
Traceback (most recent call last): File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/usr/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/ubuntu/gopath/src/github.com/iminders/tbase/tbase/run.py", line 56, in <module> main() File "/home/ubuntu/gopath/src/github.com/iminders/tbase/tbase/run.py", line 50, in main agent.learn() File "/home/ubuntu/gopath/src/github.com/iminders/tbase/tbase/agents/ddpg/agent.py", line 152, in learn sample_size=self.args.sample_size) File "/home/ubuntu/gopath/src/github.com/iminders/tbase/tbase/agents/ddpg/agent.py", line 63, in explore worker.start() File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start self._popen = self._Popen(self) File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen return Popen(process_obj) File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__ super().__init__(process_obj) File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__ self._launch(process_obj) File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 59, in _launch cmd, self._fds) File "/usr/lib/python3.6/multiprocessing/util.py", line 417, in spawnv_passfds False, False, None) OSError: [Errno 12] Cannot allocate memory Segmentation fault (core dumped)

**Comment by iminders** [comment]
https://github.com/iminders/tbase/pull/20

单进程内存占用情况：

RAM: 1.61 G
GPU: 0.54 G
2个探索进程内存占用情况：

RAM：1.67 G - 5.34 G 之间波动，然后 memory error
GPU: 0.54 G - 1.56 G 之间波动

**Comment by iminders** [comment]
增加内存到32G, 内存使用率如下图，正常运行.
建议2进程训练内存大于10G.

![image](https://user-images.githubusercontent.com/17958530/89908654-b4e21100-dc20-11ea-8e0b-b3926a42a96e.png)
